name: 'Check Issues Due Date'

on:
  schedule:
    # 한국 시간(KST) 기준 매일 오후 17시에 실행됩니다 (UTC 08:00).
    - cron: '0 8 * * *'

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Check duedate and write a comment
        uses: petrandr/duedate_reminders@latest
        with:
          # GitHub 토큰은 별도의 설정 없이 사용할 수 있습니다.
          gh_token: ${{ secrets.GITHUB_TOKEN }}

          # 알림을 설정할 GitHub 프로젝트의 실제 번호로 수정해주세요.
          project_number: 2

          # 마감일이 다가오는 이슈에 대해 알림을 보냅니다.
          notify_for: "expiring_issues"
          
          # 알림 방식을 댓글로 설정합니다.
          notification_type: "comment"
          
          # 프로젝트 보드에 설정한 마감일 필드 이름입니다.
          duedate_field_name: "Due Date"
