name: '오늘 16시55분 알림'

on:
  schedule:
    - cron: '48 7 9 9 *'  # 2025년 9월 9일 16:48 KST (UTC 07:48)

jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Check duedate and write a comment
        uses: petrandr/duedate_reminders@latest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          project_number: 2
          notify_for: "expiring_issues"
          duedate_field_name: "Due Date"
          notification_type: "comment"
