name: '매일 16시 55분 마감일 알림'

on:
  schedule:
    - cron: '37 8 * * *'
  workflow_dispatch:

# 'jobs' is at the top level
jobs:
  # 'reminder' is the job name, indented under 'jobs'
  reminder:

    # 'permissions', 'runs-on', and 'steps' are all at the SAME level,
    # indented under 'reminder'. This is the key to fixing the error.
    permissions:
      issues: write
      projects: read

    runs-on: ubuntu-latest

    steps:
      - name: 마감일 확인 및 댓글 작성
        uses: petrandr/duedate_reminders@v2
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          project_number: 2
          duedate_field_name: "Due Date"
          notify_for: "expiring_issues"
          notification_type: "comment"
